---
# fw_shutdown.yml - Shuts down a PAN-OS device.
#
# Description
# ===========
#
# This issues the shutdown command using the 'panos_op' module.  This uses the Ansible 'ignore_errors' keyword because
# issuing the shutdown command terminates the API connection.
#
# This playbook requires connection details for the device to be specified in the variables 'ip_address', 'username',
# and 'password'.  These may be defined as host variables (see `host_vars/firewall.yml` for an example) or
# extra vars.
#
# Modules Used
# ============
#
# panos_op - https://paloaltonetworks.github.io/pan-os-ansible/modules/panos_op.html
#
# Usage
# =====
#
#   $ ansible-playbook -i inventory fw_shutdown.yml

- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    device:
      ip_address: '{{ ip_address }}'
      username: '{{ username | default(omit) }}'
      password: '{{ password | default(omit) }}'
      api_key: '{{ api_key | default(omit) }}'

  tasks:
    - name: Issue firewall shutdown command
      paloaltonetworks.panos.panos_op:
        provider: '{{ device }}'
        cmd: '<request><shutdown><system></system></shutdown></request>'
        cmd_is_xml: true
      register: "cmd_output"
      failed_when: '"Command succeeded with no output" not in cmd_output.msg' # Always returns this error when succesful!
